### PR TITLE
Update KMeansSeedsAndPointsGenerator.java

### PR DESCRIPTION
**Pull request by azajaji**

### CODE REVIEW

**Comment by yousef-fadila** [comment]
can you explain to me what this code in setup-mapper do ?
If I change the x and y to float instead of int, will it be enough to
change here or I need to change the input format too?

public void setup(Context context) throws IOException {
   Configuration conf = context.getConfiguration ();
   FileSystem dfs = FileSystem.get (conf);

   Path src = new Path (conf.get ("cluster_input"));
   FSDataInputStream fs = dfs.open (src);
   BufferedReader myReader = new BufferedReader (new InputStreamReader (fs));

   String cur_line = myReader.readLine ();
   while (cur_line != null) {

      PointWritable p = new PointWritable();
      PointWritable p_copy = new PointWritable();
      try {
         Scanner reader  = new Scanner (new StringReader(cur_line));
         int x = reader.nextInt();
         int y = reader.nextInt();

         p.set(x, y);
         p_copy.set(x, y);

         prevClusters.add(p);
         newClusters.add(p_copy);

      } catch (Exception e) {
      }
      cur_line = myReader.readLine();
   }
}

**Comment by azajaji** [comment]
the important thing is (prevClusters) it contains the K centroids for this phase 
basically it will read the path assigned by the job tracker (main class) 

No you will have to change floats on the input format too because I always represents points as PointWritable and  when I read/write to files i convert them to "text text"

**Comment by azajaji** [comment]
can you tell me how to do the combiner? I can take care of floats

**Comment by yousef-fadila** [comment]
if it requires a lot of changes I will not do it.
will submit it as is

**Pull request merged**
